2020-12-23 14:12:56,804 INFO    MainThread:31417 [wandb_setup.py:_flush():70] setting env: {}
2020-12-23 14:12:56,804 INFO    MainThread:31417 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-23 14:12:56,804 INFO    MainThread:31417 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-23 14:12:56,804 INFO    MainThread:31417 [wandb_init.py:_log_setup():303] Logging user logs to /home/kim/torch_mimic/wandb/run-20201223_141256-2b2yvb75/logs/debug.log
2020-12-23 14:12:56,804 INFO    MainThread:31417 [wandb_init.py:_log_setup():304] Logging internal logs to /home/kim/torch_mimic/wandb/run-20201223_141256-2b2yvb75/logs/debug-internal.log
2020-12-23 14:12:58,116 WARNING MainThread:31417 [wandb_init.py:init():595] interrupted
Traceback (most recent call last):
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 411, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 542, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 447, in _communicate
    return future.get(timeout)
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 63, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/home/kim/anaconda3/envs/torch_rl_test/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2020-12-23 14:12:58,118 INFO    MainThread:31417 [internal.py:handle_exit():138] Internal process exited
